apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-service
spec:
  selector:
    matchLabels:
      app: geolocation-service
  replicas: 1
  template:
    metadata:
      labels:
        app: geolocation-service
    spec:
      containers:
        - name: geolocation-service
          image: <X>
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: geolocation-dynamodb-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-service
spec:
  selector:
    app: geolocation-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  resources:
    requests:
      cpu: 200m
  type: ClusterIP
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: geolocation-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geolocation-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
